export const ROUTES_NAMES = {
  LOGIN: '/auth/login',
  AUTH: '/auth',
  AUTH_CALLBACK: '/auth/callback',
  TABS: '/(tabs)',
  HOME: '/(tabs)',
  INIT: '/init',
  ONBOARDING: '/onboarding',
  WELCOME: '/onboarding/welcome',
  GOAL: '/onboarding/goal',
  EXPERIENCE: '/onboarding/experience',
  DAYS_PER_WEEK: '/onboarding/daysPerWeek',
  TIME_PER_SESSION: '/onboarding/timePerSession',
  BRIDGE: '/onboarding/bridge',
  GENDER: '/onboarding/gender',
  BIRTH_DATE: '/onboarding/birthDate',
  BODY_METRICS: '/onboarding/bodyMetrics',
  INJURIES: '/onboarding/injuries',
  PREPARING_PLAN: '/onboarding/preparingPlan',
  PREVIEW_PLAN: '/previewPlan',
  SUMMARY: '/onboarding/summary',
  PREWORKOUT: '/preworkout',
  EXERCISE_ACTIVE: '/exerciseActive',
}
